# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [15]:
# importing the NumPy library

import numpy as np

In [14]:
np.arange(5,30,5)


array([ 5, 10, 15, 20, 25])

In [16]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
import numpy as np
np_1 = np.arange(1,5)
np_2 = np.zeros(5)

In [17]:
# checking the created array: np_1
print(np_1)

[1 2 3 4]


In [18]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [ ]:
# data type of np_2


In [ ]:
# specifying the data type of the array in the provided attribute



In [ ]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

In [ ]:
# check the dimension of the arrays
# array np_1


In [ ]:
# check the dimension of the arrays
# array np_2


In [ ]:
# creating a third array with all the 5 elements as ones

np_3 = 

# checking the created array:np_3
print(np_3)

In [ ]:
# check the dimension of the arrays
# array np_2


In [30]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

NameError: name 'np_3' is not defined

In [80]:
n=4
import numpy as np
np.tile(1,n)
np.arr(np.tile(1,n),ndmin=2)

AttributeError: module 'numpy' has no attribute 'arr'

In [26]:
# creating an array of fixed length
np_4 = 

# checking the created array:np_4
print(np_4)

SyntaxError: invalid syntax (<ipython-input-26-e78f2f0ad9d2>, line 2)

In [27]:
# checking the created array:np_1
np_1

array([1, 2, 3, 4])

In [28]:
# squaring the terms of np_1


In [ ]:
# getting the absolute value of the elements


In [25]:
# np.sin()
# np.cos()

In [24]:
# np.log()

### Empty arrays

In [22]:
# Creating empty arrays

x = np.arange(1, 6)
y = 

# filling the empty array


SyntaxError: invalid syntax (<ipython-input-22-0a9ec46d79e1>, line 4)

In [23]:
# printing the output obtained above
y

NameError: name 'y' is not defined

### Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition


In [ ]:
# Cummulative addition of elements at each element


In [83]:
np.linalg

<module 'numpy.linalg' from 'C:\\Users\\Abhay\\anaconda3\\lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [12]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [19]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [20]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [10]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.1728474 , 0.34940095, 0.48451075, 0.68785844],
       [0.68037174, 0.19149569, 0.5171321 , 0.03938561],
       [0.58542276, 0.95923366, 0.44297368, 0.55912067]])

In [9]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[4, 7, 5, 1],
       [0, 2, 1, 9],
       [9, 1, 0, 4],
       [6, 4, 1, 3]])

In [79]:
n=3
import numpy as np
a=np.full((n,n),0)
a[0,]=1
a[(n-1),]=1
a[:,0]=1
a[:,(n-1)]=1
print(a)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [81]:
import numpy as np
n=6
# Create an 'n*n' array of all ones
border_array = np.ones((n, n), dtype = int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
border_array[1:-1, 1:-1] = 0

# Print the array created
print(border_array)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [84]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
m=0
n=2
b=np.array(a[m])
a[m]=a[n]
a[n]=b
a

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])

In [134]:
n=3
a=np.array([0])
b=np.array([1])

np.tile(0, (n,n))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [138]:
import numpy as np
n=4
a=np.full((n,n),0)
a[1::2]=1
a,

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

n=6
x = np.array([[0, 1], [1, 0]])
check = np.tile(x, (n//2, n//2))
print(check)

0