# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [2]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [4]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Vertical stacking - Increasing the number of row
arr_3 = np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# Checking the dimensions of the array
arr_3.ndim

2

In [9]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [13]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [44]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [46]:
# Stacking arr_5 and arr_6
np.hstack((arr_5,arr_6))

array([[ 1,  2, 20, 21, 22, 23],
       [ 3,  4, 24, 25, 26, 27],
       [ 5,  6, 28, 29, 30, 31],
       [ 7,  8, 32, 33, 34, 35],
       [ 9, 10, 36, 37, 38, 39]])

In [47]:
#Stacking vertically 
np.vstack((arr_5,arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [48]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [52]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6=arr_6.reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [54]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [62]:
p=[[1, 5],[3, 7],[4, 9]]
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [68]:
a=np.reshape(1, -1)
a.ndim


1

In [79]:
p=[[1, 5, 7]]
np.transpose(p)

array([[1],
       [5],
       [7]])

In [112]:
import numpy as np

a=np.array([[7, 13, 14],[18, 10, 17],[11, 12, 19]])
b=np.array([16, 6, 1])
c=np.array([[5, 8, 4, 3]])
d=np.vstack((a,b))
np.hstack((d,np.transpose(c)))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])