In [36]:
import numpy as np
a=[[1, 5, 9],
   [3, 0, 2]]
a=np.array(a)
b=  np.ones((8,8),dtype=int) 
print(b)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [47]:
b[6][1]=23
b

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, 23,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1]])

In [49]:
np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [89]:
 #create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'
    
# Read the input
#n = int(input())
n=7
# Import the NumPy package
import numpy as np 

# Write your code here

if n%2!=0 & n>0:
    a=np.zeros([n,n],dtype=int)
    
    a[:,n//2]=1
    a[n//2,:]=1
       
print(a)

[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
