In [3]:
100%12

4

In [7]:
import numpy as np
np.eye(2, dtype = int).reshape(4, 1).T

array([[1, 0, 0, 1]])

In [8]:
import numpy as np
a = np.arange(10)
f = np.vectorize(lambda x: x+1)
f(a)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.full((2,2), 1) == np.ones((2,2))


array([[ True,  True],
       [ True,  True]])

In [13]:
import numpy as np
a = np.array( [7, 10, 2, 4, 13, 16])
med = np.percentile(a, 50)
print(med)

8.5


In [18]:
import pandas as pd
pd.Series(np.array(range(1,10))**2, index = range(1,10))

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [19]:
n=6

import numpy as np
a=np.eye(n,dtype=int)
a[[0,-1]]=1
a[::-1]

array([[1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]])

In [29]:
n = 5  #int(input("Enter size:"))

data = np.zeros([n,n], dtype=int) # fill grid of nxn with zeros.
data[0] = data[n-1] = np.ones(n, dtype=int) # set first and last row to 1s

j = n-2
for i in range(1,n-1): # fills diagonally 1s.
    data[i][j] = 1
    j-=1
    

print(data)


[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]


In [61]:
n=[[9, 3, 2],
   [4, 0, 1],
   [9, 8, 6]]
l=np.array(n)

for i  in range(len(n)):
    

array([[9, 8, 6],
       [9, 8, 6],
       [9, 8, 6]])

In [68]:
n=[[9, 3, 2],
   [4, 0, 1]]
l=np.array(n)
len(l[1])

3